language: python
python:
  - "3.8"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
script: python -m pytest tests/
